<?xml version="1.0" encoding="Windows-1250"?>
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,comment,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>143</id>
	<name>Schema</name>
	<comment></comment>
	<entity>
		<left>410</left>
		<top>79</top>
		<width>90</width>
		<height>36</height>
		<id>34</id>
		<name>Zpevak</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>364</left>
		<top>43</top>
		<width>34</width>
		<height>12</height>
		<id>74</id>
		<name>RC</name>
		<comment>kontrolovat formát (check)</comment>
		<datatype>Number(10, 0)</datatype>
		<arbitrary>true</arbitrary>
		<ent>34</ent>
	</atribute>
	<atribute>
		<left>366</left>
		<top>13</top>
		<width>54</width>
		<height>12</height>
		<id>76</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>34</ent>
	</atribute>
	<atribute>
		<left>399</left>
		<top>28</top>
		<width>66</width>
		<height>12</height>
		<id>77</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>34</ent>
	</atribute>
	<atribute>
		<left>432</left>
		<top>46</top>
		<width>58</width>
		<height>12</height>
		<id>126</id>
		<name>adresa</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<ent>34</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>33</top>
		<width>57</width>
		<height>12</height>
		<id>127</id>
		<name>telefon</name>
		<comment></comment>
		<datatype>Number(9, 0)</datatype>
		<arbitrary>false</arbitrary>
		<ent>34</ent>
	</atribute>
	<atribute>
		<left>513</left>
		<top>53</top>
		<width>49</width>
		<height>12</height>
		<id>128</id>
		<name>email</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>false</arbitrary>
		<ent>34</ent>
	</atribute>
	<unique>
		<left>388</left>
		<top>59</top>
		<width>10</width>
		<height>10</height>
		<id>75</id>
		<name></name>
		<comment></comment>
		<ent>34</ent>
		<atr>74</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>751</left>
		<top>215</top>
		<width>90</width>
		<height>36</height>
		<id>59</id>
		<name>Saty</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>883</left>
		<top>217</top>
		<width>65</width>
		<height>12</height>
		<id>113</id>
		<name>inv_cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>59</ent>
	</atribute>
	<atribute>
		<left>881</left>
		<top>240</top>
		<width>61</width>
		<height>12</height>
		<id>112</id>
		<name>velikost</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>59</ent>
	</atribute>
	<unique>
		<left>858</left>
		<top>221</top>
		<width>10</width>
		<height>10</height>
		<id>114</id>
		<name></name>
		<comment></comment>
		<ent>59</ent>
		<atr>113</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>408</left>
		<top>313</top>
		<width>90</width>
		<height>36</height>
		<id>33</id>
		<name>Vytisk</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>479</left>
		<top>362</top>
		<width>111</width>
		<height>12</height>
		<id>111</id>
		<name>cislo_exemplare</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>33</ent>
	</atribute>
	<unique>
		<left>448</left>
		<top>363</top>
		<width>10</width>
		<height>10</height>
		<id>131</id>
		<name></name>
		<comment></comment>
		<ent>33</ent>
		<atr>111</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>411</left>
		<top>417</top>
		<width>90</width>
		<height>36</height>
		<id>20</id>
		<name>Publikace</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>540</left>
		<top>397</top>
		<width>67</width>
		<height>12</height>
		<id>119</id>
		<name>kat_cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>20</ent>
	</atribute>
	<atribute>
		<left>540</left>
		<top>445</top>
		<width>64</width>
		<height>12</height>
		<id>27</id>
		<name>varianta</name>
		<comment>zda se jedná o partituru, nebo o part a pro který hlas</comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>false</arbitrary>
		<ent>20</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>467</top>
		<width>85</width>
		<height>12</height>
		<id>23</id>
		<name>pocet_stran</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>20</ent>
	</atribute>
	<atribute>
		<left>541</left>
		<top>422</top>
		<width>66</width>
		<height>12</height>
		<id>129</id>
		<name>nazev_p</name>
		<comment></comment>
		<datatype>VarChar2(100)</datatype>
		<arbitrary>true</arbitrary>
		<ent>20</ent>
	</atribute>
	<unique>
		<left>519</left>
		<top>406</top>
		<width>10</width>
		<height>10</height>
		<id>120</id>
		<name></name>
		<comment></comment>
		<ent>20</ent>
		<atr>119</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>738</left>
		<top>378</top>
		<width>106</width>
		<height>124</height>
		<id>49</id>
		<name>Udalost</name>
		<comment></comment>
	</entity>
	<entity>
		<left>746</left>
		<top>414</top>
		<width>90</width>
		<height>36</height>
		<id>80</id>
		<name>Koncert</name>
		<comment></comment>
		<parent>49</parent>
	</entity>
	<atribute>
		<left>871</left>
		<top>419</top>
		<width>63</width>
		<height>12</height>
		<id>81</id>
		<name>vstupne</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>80</ent>
	</atribute>
	<atribute>
		<left>869</left>
		<top>444</top>
		<width>56</width>
		<height>12</height>
		<id>82</id>
		<name>divaku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>80</ent>
	</atribute>
	<entity>
		<left>746</left>
		<top>458</top>
		<width>90</width>
		<height>36</height>
		<id>79</id>
		<name>Zkouska</name>
		<comment></comment>
		<parent>49</parent>
	</entity>
	<atribute>
		<left>869</left>
		<top>471</top>
		<width>92</width>
		<height>12</height>
		<id>115</id>
		<name>je_generalka</name>
		<comment>logická hodnota</comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>79</ent>
	</atribute>
	<atribute>
		<left>919</left>
		<top>371</top>
		<width>37</width>
		<height>12</height>
		<id>56</id>
		<name>cas</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>49</ent>
	</atribute>
	<atribute>
		<left>919</left>
		<top>392</top>
		<width>49</width>
		<height>12</height>
		<id>57</id>
		<name>misto</name>
		<comment></comment>
		<datatype>VarChar2(100)</datatype>
		<arbitrary>true</arbitrary>
		<ent>49</ent>
	</atribute>
	<unique>
		<left>876</left>
		<top>382</top>
		<width>10</width>
		<height>10</height>
		<id>118</id>
		<name></name>
		<comment></comment>
		<ent>49</ent>
		<atr>57</atr>
		<atr>56</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>595</left>
		<top>528</top>
		<width>90</width>
		<height>36</height>
		<id>68</id>
		<name>Cast_skladby</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>654</left>
		<top>580</top>
		<width>64</width>
		<height>12</height>
		<id>85</id>
		<name>nazev_c</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>true</arbitrary>
		<ent>68</ent>
	</atribute>
	<atribute>
		<left>606</left>
		<top>597</top>
		<width>56</width>
		<height>12</height>
		<id>86</id>
		<name>poradi</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>68</ent>
	</atribute>
	<unique>
		<left>600</left>
		<top>574</top>
		<width>10</width>
		<height>10</height>
		<id>137</id>
		<name></name>
		<comment></comment>
		<ent>68</ent>
		<atr>86</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>403</left>
		<top>635</top>
		<width>106</width>
		<height>36</height>
		<id>12</id>
		<name>Skladba</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>473</left>
		<top>705</top>
		<width>56</width>
		<height>12</height>
		<id>63</id>
		<name>durata</name>
		<comment>delka skladby v sec (nebo lze pou?ít typ interval)</comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>489</left>
		<top>683</top>
		<width>58</width>
		<height>12</height>
		<id>104</id>
		<name>opus_c</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>457</left>
		<top>729</top>
		<width>80</width>
		<height>12</height>
		<id>22</id>
		<name>rok_vzniku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>397</left>
		<top>692</top>
		<width>52</width>
		<height>12</height>
		<id>21</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>363</left>
		<top>704</top>
		<width>29</width>
		<height>12</height>
		<id>124</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>12</ent>
	</atribute>
	<unique>
		<left>375</left>
		<top>678</top>
		<width>10</width>
		<height>10</height>
		<id>125</id>
		<name></name>
		<comment></comment>
		<ent>12</ent>
		<atr>124</atr>
		<primary>true</primary>
	</unique>
	<relation>
		<left>401</left>
		<top>516</top>
		<width>120</width>
		<height>36</height>
		<id>30</id>
		<name>Zarazeni</name>
		<comment></comment>
	</relation>
	<atribute>
		<left>503</left>
		<top>502</top>
		<width>56</width>
		<height>12</height>
		<id>133</id>
		<name>poradi</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<rel>30</rel>
	</atribute>
	<relation>
		<left>567</left>
		<top>281</top>
		<width>120</width>
		<height>36</height>
		<id>52</id>
		<name>Ucast</name>
		<comment></comment>
	</relation>
	<atribute>
		<left>621</left>
		<top>334</top>
		<width>70</width>
		<height>12</height>
		<id>55</id>
		<name>pritomen</name>
		<comment>logická hodnota</comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<rel>52</rel>
	</atribute>
	<relation>
		<left>400</left>
		<top>216</top>
		<width>120</width>
		<height>36</height>
		<id>42</id>
		<name>Zapujcka_not</name>
		<comment></comment>
	</relation>
	<relation>
		<left>111</left>
		<top>635</top>
		<width>120</width>
		<height>36</height>
		<id>14</id>
		<name>Autorstvi</name>
		<comment></comment>
	</relation>
	<atribute>
		<left>221</left>
		<top>614</top>
		<width>75</width>
		<height>12</height>
		<id>134</id>
		<name>je_uprava</name>
		<comment>logická hodnota</comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<rel>14</rel>
	</atribute>
	<cardinality>
		<left>596</left>
		<top>84</top>
		<width>49</width>
		<height>27</height>
		<id>62</id>
		<name>nositel</name>
		<comment></comment>
		<ent>34</ent>
		<rel>60</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>584</left>
		<top>640</top>
		<width>109</width>
		<height>27</height>
		<id>48</id>
		<name>zpivana_skladba</name>
		<comment></comment>
		<ent>12</ent>
		<rel>46</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>593</left>
		<top>184</top>
		<width>59</width>
		<height>27</height>
		<id>53</id>
		<name>ucastnik</name>
		<comment></comment>
		<ent>34</ent>
		<rel>52</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>419</left>
		<top>575</top>
		<width>72</width>
		<height>27</height>
		<id>31</id>
		<name>p_skladba</name>
		<comment></comment>
		<ent>12</ent>
		<rel>30</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>413</left>
		<top>266</top>
		<width>83</width>
		<height>27</height>
		<id>44</id>
		<name>pujceny_kus</name>
		<comment></comment>
		<ent>33</ent>
		<rel>42</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>752</left>
		<top>142</top>
		<width>87</width>
		<height>27</height>
		<id>61</id>
		<name>pujcene_saty</name>
		<comment></comment>
		<ent>59</ent>
		<rel>60</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>290</left>
		<top>85</top>
		<width>35</width>
		<height>27</height>
		<id>37</id>
		<name>clen</name>
		<comment></comment>
		<ent>34</ent>
		<rel>36</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>309</left>
		<top>639</top>
		<width>34</width>
		<height>27</height>
		<id>15</id>
		<name>dilo</name>
		<comment></comment>
		<ent>12</ent>
		<rel>14</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>421</left>
		<top>466</top>
		<width>68</width>
		<height>27</height>
		<id>32</id>
		<name>publikace</name>
		<comment></comment>
		<ent>20</ent>
		<rel>30</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>431</left>
		<top>140</top>
		<width>49</width>
		<height>27</height>
		<id>43</id>
		<name>drzitel</name>
		<comment></comment>
		<ent>34</ent>
		<rel>42</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>764</left>
		<top>285</top>
		<width>54</width>
		<height>27</height>
		<id>54</id>
		<name>udalost</name>
		<comment></comment>
		<ent>49</ent>
		<rel>52</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>772</left>
		<top>553</top>
		<width>39</width>
		<height>27</height>
		<id>51</id>
		<name>akce</name>
		<comment></comment>
		<ent>49</ent>
		<rel>46</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>139</left>
		<top>141</top>
		<width>57</width>
		<height>27</height>
		<id>38</id>
		<name>skupina</name>
		<comment></comment>
		<ent>35</ent>
		<rel>36</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>144</left>
		<top>562</top>
		<width>42</width>
		<height>27</height>
		<id>16</id>
		<name>autor</name>
		<comment></comment>
		<ent>11</ent>
		<rel>14</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<strong>
		<left>507</left>
		<top>576</top>
		<width>4</width>
		<height>4</height>
		<ent>12</ent>
		<uni>137</uni>
	</strong>
	<relation>
		<left>113</left>
		<top>81</top>
		<width>120</width>
		<height>36</height>
		<id>36</id>
		<name>Prislusnost</name>
		<comment></comment>
	</relation>
	<relation>
		<left>731</left>
		<top>632</top>
		<width>128</width>
		<height>44</height>
		<id>46</id>
		<name>Cast_programu</name>
		<comment></comment>
	</relation>
	<atribute>
		<left>834</left>
		<top>611</top>
		<width>56</width>
		<height>12</height>
		<id>132</id>
		<name>poradi</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<rel>46</rel>
	</atribute>
	<entity>
		<left>119</left>
		<top>492</top>
		<width>90</width>
		<height>36</height>
		<id>11</id>
		<name>Skladatel</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>153</left>
		<top>436</top>
		<width>54</width>
		<height>12</height>
		<id>64</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>11</ent>
	</atribute>
	<atribute>
		<left>237</left>
		<top>485</top>
		<width>93</width>
		<height>12</height>
		<id>66</id>
		<name>rok_narozeni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>11</ent>
	</atribute>
	<atribute>
		<left>238</left>
		<top>503</top>
		<width>73</width>
		<height>12</height>
		<id>67</id>
		<name>rok_umrti</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>11</ent>
	</atribute>
	<atribute>
		<left>182</left>
		<top>454</top>
		<width>66</width>
		<height>12</height>
		<id>65</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>11</ent>
	</atribute>
	<unique>
		<left>161</left>
		<top>471</top>
		<width>10</width>
		<height>10</height>
		<id>123</id>
		<name></name>
		<comment></comment>
		<ent>11</ent>
		<atr>64</atr>
		<atr>65</atr>
		<primary>true</primary>
	</unique>
	<relation>
		<left>729</left>
		<top>75</top>
		<width>127</width>
		<height>46</height>
		<id>60</id>
		<name>Zapujcka_satu</name>
		<comment></comment>
	</relation>
	<strong>
		<left>451</left>
		<top>411</top>
		<width>4</width>
		<height>4</height>
		<ent>20</ent>
		<uni>131</uni>
	</strong>
	<entity>
		<left>115</left>
		<top>201</top>
		<width>106</width>
		<height>36</height>
		<id>35</id>
		<name>Hlas</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>196</left>
		<top>247</top>
		<width>65</width>
		<height>12</height>
		<id>136</id>
		<name>nazev_h</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>35</ent>
	</atribute>
	<unique>
		<left>162</left>
		<top>249</top>
		<width>10</width>
		<height>10</height>
		<id>84</id>
		<name></name>
		<comment></comment>
		<ent>35</ent>
		<atr>83</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>160</left>
		<top>268</top>
		<width>62</width>
		<height>12</height>
		<id>83</id>
		<name>zkratka</name>
		<comment></comment>
		<datatype>VarChar2(5)</datatype>
		<arbitrary>true</arbitrary>
		<ent>35</ent>
	</atribute>
	<relation>
		<left>237</left>
		<top>141</top>
		<width>120</width>
		<height>36</height>
		<id>139</id>
		<name>Vedeni</name>
		<comment></comment>
	</relation>
	<cardinality>
		<left>345</left>
		<top>116</top>
		<width>56</width>
		<height>27</height>
		<id>140</id>
		<name>vedouci</name>
		<comment></comment>
		<ent>34</ent>
		<rel>139</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>264</left>
		<top>205</top>
		<width>54</width>
		<height>27</height>
		<id>141</id>
		<name>vedena</name>
		<comment></comment>
		<ent>35</ent>
		<rel>139</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
</schema>
