=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/prg036_viezan_lukas/data.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- objednavky = korenovy element -->
<!ELEMENT objednavky (obchod)>
  <!ELEMENT obchod (objednavka)>
    <!ELEMENT objednavka (datum, zbozi, zakaznik, poznamka?)>
      <!ELEMENT datum (#PCDATA)>  
      <!ELEMENT zbozi (vyrobek+, podtrzeni)>
        <!ELEMENT vyrobek (#PCDATA)>
        <!ELEMENT podtrzeni EMPTY>
      <!ELEMENT zakaznik (jmeno, email, telefon?, adresa_bydliste, adresa_dorucovaci?)>
        <!ELEMENT jmeno (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT telefon (#PCDATA)>
        <!ELEMENT adresa_bydliste (ulice, popisne_cislo, psc, mesto)>
          <!ELEMENT ulice (#PCDATA)>
          <!ELEMENT popisne_cislo (#PCDATA)>
          <!ELEMENT psc (#PCDATA)>
          <!ELEMENT mesto (#PCDATA)>
        <!ELEMENT adresa_dorucovaci (ulice, popisne_cislo, psc, mesto)>
        <!ELEMENT poznamka (#PCDATA|odkaz)*>
          <!ELEMENT odkaz (#PCDATA)>

<!ATTLIST obchod id_obchodu ID #REQUIRED>
<!ATTLIST objednavka stav (odeslána|doručena|nevyřízena) #REQUIRED>
<!ATTLIST vyrobek id ID #REQUIRED>
<!ATTLIST vyrobek cena CDATA #REQUIRED>
<!ATTLIST vyrobek ks CDATA #REQUIRED>
<!ATTLIST zakaznik id ID #REQUIRED>
<!ATTLIST odkaz naid IDREF #IMPLIED>

<!ENTITY autor "Vytvořil: Lukáš Viezán">

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/prg036_viezan_lukas/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE objednavky SYSTEM "data.dtd">
<objednavky>
  <obchod id_obchodu="ID32">
    <objednavka stav="odeslána">
      <datum>12.12.1212</datum>
      <zbozi>
      <!-- Výpis všech objednaných produktů -->
        <vyrobek id="ID323321" cena="6562" ks="2">Monitor</vyrobek>
        <vyrobek id="ID763276" cena="576" ks="3">Myš</vyrobek>
        <vyrobek id="ID872175" cena="786" ks="3">Klávesnice</vyrobek>
        <vyrobek id="ID135216" cena="18" ks="120">CD</vyrobek>
        <vyrobek id="ID126712" cena="2389" ks="1">Tiskárna</vyrobek>
        <vyrobek id="ID317633" cena="2798" ks="1">Scaner</vyrobek>
        <vyrobek id="ID126671" cena="12083" ks="1">Notebook</vyrobek>
        <vyrobek id="ID561672" cena="1297" ks="2">DVD Mechanika</vyrobek>
        <vyrobek id="ID091923" cena="2879" ks="3">RAM Paměť</vyrobek>
        <vyrobek id="ID361286" cena="1298" ks="1">Harddisk</vyrobek>
        <podtrzeni />
      </zbozi>
      <zakaznik id="ID21577">
        <jmeno>Lukáš Viezán</jmeno>
        <email>viezaluk@fel.cvut.cz</email>
        <telefon>123 456 789</telefon>
        <adresa_bydliste>
          <ulice>Nekonečná</ulice>
          <popisne_cislo>1200</popisne_cislo>
          <psc>12087</psc>
          <mesto>Praha 9</mesto>
        </adresa_bydliste>
        <adresa_dorucovaci>
          <ulice>Nekonečná</ulice>
          <popisne_cislo>1200</popisne_cislo>
          <psc>12087</psc>
          <mesto>Brno</mesto>
        </adresa_dorucovaci>
      </zakaznik>
      <poznamka>
       <![CDATA[Opovažte se rozbít můj drahocený ]]>&autor;
        <odkaz naid="ID323321">Monitor</odkaz>
      </poznamka>
    </objednavka>
    
    <objednavka stav="odeslána">
      <datum>12.12.1212</datum>
      <zbozi>
      <!-- Výpis všech objednaných produktů -->
        <vyrobek id="ID323321" cena="6562" ks="2">Monitor</vyrobek>
        <vyrobek id="ID763276" cena="576" ks="3">Myš</vyrobek>
        <vyrobek id="ID872175" cena="786" ks="3">Klávesnice</vyrobek>
        <podtrzeni />
      </zbozi>
      <zakaznik id="ID21577">
        <jmeno>Lukáš Viezán</jmeno>
        <email>viezaluk@fel.cvut.cz</email>
        <telefon>123 456 789</telefon>
        <adresa_bydliste>
          <ulice>Nekonečná</ulice>
          <popisne_cislo>1200</popisne_cislo>
          <psc>12087</psc>
          <mesto>Praha 10</mesto>
        </adresa_bydliste>
        <adresa_dorucovaci>
          <ulice>Nekonečná</ulice>
          <popisne_cislo>1200</popisne_cislo>
          <psc>12087</psc>
          <mesto>Praha 10</mesto>
        </adresa_dorucovaci>
      </zakaznik>
      <poznamka>
       <![CDATA[Opovažte se rozbít můj drahocený ]]>&autor;
        <odkaz naid="ID872175">Klávesnice</odkaz>
      </poznamka>
    </objednavka>
    
    <objednavka stav="odeslána">
      <datum>12.12.1212</datum>
      <zbozi>
      <!-- Výpis všech objednaných produktů -->
        <vyrobek id="ID323321" cena="6562" ks="2">Monitor</vyrobek>
        <vyrobek id="ID126712" cena="2389" ks="1">Tiskárna</vyrobek>
        <vyrobek id="ID317633" cena="2798" ks="1">Scaner</vyrobek>
        <vyrobek id="ID126671" cena="12083" ks="1">Notebook</vyrobek>
        <vyrobek id="ID561672" cena="1297" ks="2">DVD Mechanika</vyrobek>
        <vyrobek id="ID091923" cena="2879" ks="3">RAM Paměť</vyrobek>
        <vyrobek id="ID361286" cena="1298" ks="1">Harddisk</vyrobek>
        <podtrzeni />
      </zbozi>
      <zakaznik id="ID21577">
        <jmeno>Lukáš Viezán</jmeno>
        <email>viezaluk@fel.cvut.cz</email>
        <telefon>123 456 789</telefon>
        <adresa_bydliste>
          <ulice>Nekonečná</ulice>
          <popisne_cislo>1200</popisne_cislo>
          <psc>12087</psc>
          <mesto>Praha 10</mesto>
        </adresa_bydliste>
      </zakaznik>
      <poznamka>
       <![CDATA[Opovažte se rozbít můj drahocený ]]>&autor;
        <odkaz naid="ID361286">HDD</odkaz>
      </poznamka>
    </objednavka>
  </obchod>
  
  <?php echo date; ?> 
   
</objednavky>
