=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/XML/slunecni soustava/slunecni_soustava.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/slunecni_soustava.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE slunecni_soustava SYSTEM "slunecni_soustava.dtd">

    <slunecni_soustava>
    ...
    </slunecni_soustava>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT slunecni_soustava (planeta)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT planeta (#PCDATA|(satelity,skupenstvi,doba_obehu,vzdalenost_od_slunce,hustota,polomer,jmeno)?)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT jmeno (#PCDATA)>
<!ATTLIST jmeno
    jazyk CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT polomer (#PCDATA)>
<!ATTLIST polomer
    jednotka CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hustota (#PCDATA)>
<!ATTLIST hustota
    jednotka CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT vzdalenost_od_slunce (afelium|perihelium)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT perihelium (#PCDATA)>
<!ATTLIST perihelium
    jednotka CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT afelium (#PCDATA)>
<!ATTLIST afelium
    jednotka CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT doba_obehu (kolem_osy|kolem_slunce)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT kolem_slunce (#PCDATA)>
<!ATTLIST kolem_slunce
    jednotka CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT kolem_osy (#PCDATA)>
<!ATTLIST kolem_osy
    jednotka CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT skupenstvi (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT satelity (mesic)*>
<!ATTLIST satelity
    pocet CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT mesic (polomer)*>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/XML/slunecni soustava/slunecni_soustava.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE slunecni_soustava SYSTEM "slunecni_soustava.dtd">
<!--
    Document   : slunecni_soustava.xml
    Created on : 1. duben 2010, 9:55
    Author     : woxie
    Description:
        Purpose of the document follows.
-->

<slunecni_soustava>
    <planeta>
        <jmeno jazyk="CZ">Zeme</jmeno>
        <jmeno jazyk="LAT">GAIA</jmeno>
        <polomer jednotka="km">6378</polomer>
        <hustota jednotka="kg/m^3">5 515</hustota>

        <vzdalenost_od_slunce>
            <perihelium jednotka="km">
                147 098 074
            </perihelium>
            <afelium jednotka="km">
                152 097 701
            </afelium>
        </vzdalenost_od_slunce>

        <doba_obehu>
            <kolem_slunce jednotka="den">
                365,256
            </kolem_slunce>
            <kolem_osy jednotka="h">
                23,934 h
            </kolem_osy>
        </doba_obehu>
        pevne
        <skupenstvi>

        </skupenstvi>

        <satelity pocet="1">
            <mesic>
                <polomer jednotka="km">
                    	3 476,2
                </polomer>
            </mesic>
        </satelity>
    </planeta>


    <planeta>
        <jmeno jazyk="CZ">Merkur</jmeno>
        <polomer jednotka="km">2439,7</polomer>
        <hustota jednotka="kg/m^3">5400</hustota>

        <vzdalenost_od_slunce>
            <perihelium jednotka="km">
                46 001 272
            </perihelium>
            <afelium jednotka="km">
               69 817 079
            </afelium>
        </vzdalenost_od_slunce>

        <doba_obehu>
            <kolem_slunce jednotka="den">
                	87,969
            </kolem_slunce>
            <kolem_osy jednotka="den">
                115.88
            </kolem_osy>
        </doba_obehu>
        pevne
        <skupenstvi>

            </skupenstvi>

        <satelity pocet="1">
            <mesic>
                <polomer jednotka="km">
                    	3 476,2
                </polomer>
            </mesic>
        </satelity>
    </planeta>

</slunecni_soustava>
