<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ER Modeller version 4.0 schema -->
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,notation,comment,usertype*,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT usertype (typename, datatypedef)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT typename (#PCDATA)>
<!ELEMENT datatypedef (datatype, item*)>
<!ELEMENT item (itemname, datatype)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>166</id>
	<name>Schema</name>
	<notation>2</notation>
	<comment></comment>
	<entity>
		<left>425</left>
		<top>264</top>
		<width>197</width>
		<height>130</height>
		<id>13</id>
		<name>osoba</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>430</left>
		<top>294</top>
		<width>29</width>
		<height>13</height>
		<id>96</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>13</ent>
	</atribute>
	<atribute>
		<left>430</left>
		<top>314</top>
		<width>54</width>
		<height>13</height>
		<id>97</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>13</ent>
	</atribute>
	<atribute>
		<left>430</left>
		<top>334</top>
		<width>64</width>
		<height>13</height>
		<id>98</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>13</ent>
	</atribute>
	<cardinality>
		<left>622</left>
		<top>325</top>
		<width>56</width>
		<height>29</height>
		<id>15</id>
		<name>byl hran</name>
		<comment></comment>
		<ent>13</ent>
		<rel>14</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>780</left>
		<top>261</top>
		<width>187</width>
		<height>99</height>
		<id>12</id>
		<name>Deck</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>785</left>
		<top>291</top>
		<width>29</width>
		<height>13</height>
		<id>53</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>785</left>
		<top>311</top>
		<width>54</width>
		<height>13</height>
		<id>136</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>785</left>
		<top>331</top>
		<width>47</width>
		<height>13</height>
		<id>137</id>
		<name>barvy</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>12</ent>
	</atribute>
	<cardinality>
		<left>967</left>
		<top>285</top>
		<width>72</width>
		<height>29</height>
		<id>24</id>
		<name>MTG_karta</name>
		<comment></comment>
		<ent>12</ent>
		<rel>23</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>810</left>
		<top>233</top>
		<width>38</width>
		<height>29</height>
		<id>59</id>
		<name>druh</name>
		<comment></comment>
		<ent>12</ent>
		<rel>58</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>740</left>
		<top>324</top>
		<width>41</width>
		<height>29</height>
		<id>16</id>
		<name>hrala</name>
		<comment></comment>
		<ent>12</ent>
		<rel>14</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>825</left>
		<top>360</top>
		<width>96</width>
		<height>29</height>
		<id>88</id>
		<name>hral_na_turnaji</name>
		<comment></comment>
		<ent>12</ent>
		<rel>86</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>180</left>
		<top>596</top>
		<width>200</width>
		<height>99</height>
		<id>143</id>
		<name>system</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>185</left>
		<top>646</top>
		<width>50</width>
		<height>13</height>
		<id>148</id>
		<name>popis</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>143</ent>
	</atribute>
	<atribute>
		<left>185</left>
		<top>626</top>
		<width>50</width>
		<height>13</height>
		<id>147</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>143</ent>
	</atribute>
	<atribute>
		<left>185</left>
		<top>666</top>
		<width>29</width>
		<height>13</height>
		<id>156</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>3</position>
		<ent>143</ent>
	</atribute>
	<cardinality>
		<left>252</left>
		<top>568</top>
		<width>57</width>
		<height>29</height>
		<id>145</id>
		<name>byl_syst</name>
		<comment></comment>
		<ent>143</ent>
		<rel>144</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>394</left>
		<top>703</top>
		<width>183</width>
		<height>133</height>
		<id>160</id>
		<name>format</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>399</left>
		<top>733</top>
		<width>29</width>
		<height>13</height>
		<id>161</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>160</ent>
	</atribute>
	<atribute>
		<left>399</left>
		<top>753</top>
		<width>50</width>
		<height>13</height>
		<id>162</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>160</ent>
	</atribute>
	<cardinality>
		<left>487</left>
		<top>675</top>
		<width>76</width>
		<height>29</height>
		<id>164</id>
		<name>mel_format</name>
		<comment></comment>
		<ent>160</ent>
		<rel>163</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>662</left>
		<top>750</top>
		<width>228</width>
		<height>79</height>
		<id>130</id>
		<name>vysledek</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>667</left>
		<top>800</top>
		<width>120</width>
		<height>13</height>
		<id>135</id>
		<name>hrac_2_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>130</ent>
	</atribute>
	<atribute>
		<left>667</left>
		<top>780</top>
		<width>120</width>
		<height>13</height>
		<id>131</id>
		<name>hrac_1_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>130</ent>
	</atribute>
	<cardinality>
		<left>708</left>
		<top>722</top>
		<width>85</width>
		<height>29</height>
		<id>134</id>
		<name>s_vysledkem</name>
		<comment></comment>
		<ent>130</ent>
		<rel>132</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>939</left>
		<top>713</top>
		<width>207</width>
		<height>119</height>
		<id>105</id>
		<name>zapas</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>944</left>
		<top>763</top>
		<width>57</width>
		<height>13</height>
		<id>110</id>
		<name>hrac_2</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>105</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>743</top>
		<width>57</width>
		<height>13</height>
		<id>109</id>
		<name>hrac_1</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>105</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>783</top>
		<width>74</width>
		<height>13</height>
		<id>139</id>
		<name>poznamky</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>105</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>803</top>
		<width>38</width>
		<height>13</height>
		<id>140</id>
		<name>bye</name>
		<comment></comment>
		<datatype>Char(1)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>105</ent>
	</atribute>
	<cardinality>
		<left>887</left>
		<top>715</top>
		<width>53</width>
		<height>29</height>
		<id>133</id>
		<name>zapasu</name>
		<comment></comment>
		<ent>105</ent>
		<rel>132</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1146</left>
		<top>732</top>
		<width>36</width>
		<height>29</height>
		<id>107</id>
		<name>kola</name>
		<comment></comment>
		<ent>105</ent>
		<rel>106</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>860</left>
		<top>498</top>
		<width>183</width>
		<height>79</height>
		<id>47</id>
		<name>typ</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>865</left>
		<top>528</top>
		<width>50</width>
		<height>13</height>
		<id>51</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>47</ent>
	</atribute>
	<atribute>
		<left>865</left>
		<top>548</top>
		<width>29</width>
		<height>13</height>
		<id>153</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>47</ent>
	</atribute>
	<cardinality>
		<left>932</left>
		<top>470</top>
		<width>34</width>
		<height>29</height>
		<id>50</id>
		<name>typ</name>
		<comment></comment>
		<ent>47</ent>
		<rel>48</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>997</left>
		<top>321</top>
		<width>222</width>
		<height>139</height>
		<id>19</id>
		<name>MTG_karta</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>1002</left>
		<top>351</top>
		<width>89</width>
		<height>13</height>
		<id>27</id>
		<name>casting_cost</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>411</top>
		<width>103</width>
		<height>13</height>
		<id>83</id>
		<name>sb_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>371</top>
		<width>54</width>
		<height>13</height>
		<id>52</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>431</top>
		<width>29</width>
		<height>13</height>
		<id>154</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>5</position>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>391</top>
		<width>107</width>
		<height>13</height>
		<id>81</id>
		<name>md_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>19</ent>
	</atribute>
	<cardinality>
		<left>1092</left>
		<top>293</top>
		<width>65</width>
		<height>29</height>
		<id>84</id>
		<name>obsahuje</name>
		<comment></comment>
		<ent>19</ent>
		<rel>23</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1219</left>
		<top>344</top>
		<width>43</width>
		<height>29</height>
		<id>31</id>
		<name>barva</name>
		<comment></comment>
		<ent>19</ent>
		<rel>30</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1104</left>
		<top>460</top>
		<width>40</width>
		<height>29</height>
		<id>49</id>
		<name>karta</name>
		<comment></comment>
		<ent>19</ent>
		<rel>48</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>934</left>
		<top>598</top>
		<width>267</width>
		<height>79</height>
		<id>99</id>
		<name>kolo</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>939</left>
		<top>628</top>
		<width>45</width>
		<height>13</height>
		<id>103</id>
		<name>cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>99</ent>
	</atribute>
	<cardinality>
		<left>890</left>
		<top>619</top>
		<width>44</width>
		<height>29</height>
		<id>102</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>99</ent>
		<rel>100</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>1011</left>
		<top>677</top>
		<width>46</width>
		<height>29</height>
		<id>108</id>
		<name>zapas</name>
		<comment></comment>
		<ent>99</ent>
		<rel>106</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>1137</left>
		<top>507</top>
		<width>183</width>
		<height>79</height>
		<id>29</id>
		<name>barva</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>1142</left>
		<top>557</top>
		<width>29</width>
		<height>13</height>
		<id>159</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>29</ent>
	</atribute>
	<atribute>
		<left>1142</left>
		<top>537</top>
		<width>50</width>
		<height>13</height>
		<id>45</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>29</ent>
	</atribute>
	<cardinality>
		<left>1167</left>
		<top>479</top>
		<width>64</width>
		<height>29</height>
		<id>32</id>
		<name>ma barvu</name>
		<comment></comment>
		<ent>29</ent>
		<rel>30</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>152</left>
		<top>411</top>
		<width>197</width>
		<height>139</height>
		<id>121</id>
		<name>rozhodci</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>157</left>
		<top>481</top>
		<width>44</width>
		<height>13</height>
		<id>129</id>
		<name>level</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>121</ent>
	</atribute>
	<atribute>
		<left>157</left>
		<top>521</top>
		<width>29</width>
		<height>13</height>
		<id>158</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>5</position>
		<ent>121</ent>
	</atribute>
	<atribute>
		<left>157</left>
		<top>461</top>
		<width>64</width>
		<height>13</height>
		<id>128</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>121</ent>
	</atribute>
	<atribute>
		<left>157</left>
		<top>441</top>
		<width>54</width>
		<height>13</height>
		<id>127</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>121</ent>
	</atribute>
	<atribute>
		<left>157</left>
		<top>501</top>
		<width>51</width>
		<height>13</height>
		<id>150</id>
		<name>hlavni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>121</ent>
	</atribute>
	<cardinality>
		<left>349</left>
		<top>416</top>
		<width>83</width>
		<height>29</height>
		<id>124</id>
		<name>Rozhodcoval</name>
		<comment></comment>
		<ent>121</ent>
		<rel>122</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>276</left>
		<top>176</top>
		<width>183</width>
		<height>79</height>
		<id>57</id>
		<name>druh</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>281</left>
		<top>226</top>
		<width>29</width>
		<height>13</height>
		<id>157</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>57</ent>
	</atribute>
	<atribute>
		<left>281</left>
		<top>206</top>
		<width>50</width>
		<height>13</height>
		<id>61</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>57</ent>
	</atribute>
	<cardinality>
		<left>459</left>
		<top>181</top>
		<width>41</width>
		<height>29</height>
		<id>60</id>
		<name>Deck</name>
		<comment></comment>
		<ent>57</ent>
		<rel>58</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>537</left>
		<top>407</top>
		<width>227</width>
		<height>239</height>
		<id>41</id>
		<name>turnaj</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>542</left>
		<top>517</top>
		<width>110</width>
		<height>13</height>
		<id>126</id>
		<name>dolarova_dotace</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>5</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>537</top>
		<width>83</width>
		<height>13</height>
		<id>138</id>
		<name>jina_dotace</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>6</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>577</top>
		<width>62</width>
		<height>13</height>
		<id>152</id>
		<name>vstupne</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>8</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>437</top>
		<width>94</width>
		<height>13</height>
		<id>42</id>
		<name>misto_konani</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>457</top>
		<width>54</width>
		<height>13</height>
		<id>43</id>
		<name>datum</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>477</top>
		<width>50</width>
		<height>13</height>
		<id>54</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>597</top>
		<width>29</width>
		<height>13</height>
		<id>155</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>9</position>
		<ent>41</ent>
	</atribute>
	<atribute>
		<left>542</left>
		<top>497</top>
		<width>109</width>
		<height>13</height>
		<id>56</id>
		<name>pocet_ucastniku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>41</ent>
	</atribute>
	<cardinality>
		<left>764</left>
		<top>577</top>
		<width>36</width>
		<height>29</height>
		<id>101</id>
		<name>kolo</name>
		<comment></comment>
		<ent>41</ent>
		<rel>100</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>625</left>
		<top>379</top>
		<width>52</width>
		<height>29</height>
		<id>87</id>
		<name>balicek</name>
		<comment></comment>
		<ent>41</ent>
		<rel>86</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>437</left>
		<top>479</top>
		<width>101</width>
		<height>29</height>
		<id>123</id>
		<name>mel_rozhodciho</name>
		<comment></comment>
		<ent>41</ent>
		<rel>122</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>413</left>
		<top>571</top>
		<width>124</width>
		<height>29</height>
		<id>146</id>
		<name>byl_hran_podle_sys</name>
		<comment></comment>
		<ent>41</ent>
		<rel>144</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>646</left>
		<top>646</top>
		<width>77</width>
		<height>29</height>
		<id>165</id>
		<name>byl_formatu</name>
		<comment></comment>
		<ent>41</ent>
		<rel>163</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<atribute>
		<left>542</left>
		<top>557</top>
		<width>43</width>
		<height>13</height>
		<id>149</id>
		<name>top8</name>
		<comment>popisuje, jestli ma turnaj TOP 8</comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>7</position>
		<ent>41</ent>
	</atribute>
	<relation>
		<left>377</left>
		<top>567</top>
		<width>7</width>
		<height>7</height>
		<id>144</id>
		<name>byl_pouzit</name>
		<comment></comment>
	</relation>
	<relation>
		<left>465</left>
		<top>447</top>
		<width>7</width>
		<height>7</height>
		<id>122</id>
		<name>byl_rozhodcim</name>
		<comment></comment>
	</relation>
	<relation>
		<left>601</left>
		<top>668</top>
		<width>7</width>
		<height>7</height>
		<id>163</id>
		<name>je_formatu</name>
		<comment></comment>
	</relation>
	<relation>
		<left>842</left>
		<top>712</top>
		<width>7</width>
		<height>7</height>
		<id>132</id>
		<name>byl_dohran</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1182</left>
		<top>708</top>
		<width>7</width>
		<height>7</height>
		<id>106</id>
		<name>hraji_se_zapasy</name>
		<comment></comment>
	</relation>
	<relation>
		<left>830</left>
		<top>583</top>
		<width>7</width>
		<height>7</height>
		<id>100</id>
		<name>bylo_soucasti_turnaje</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1010</left>
		<top>480</top>
		<width>7</width>
		<height>7</height>
		<id>48</id>
		<name>ma_typ</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1222</left>
		<top>461</top>
		<width>7</width>
		<height>7</height>
		<id>30</id>
		<name>je_barvy</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1050</left>
		<top>299</top>
		<width>7</width>
		<height>7</height>
		<id>23</id>
		<name>obsahuje</name>
		<comment></comment>
	</relation>
	<relation>
		<left>730</left>
		<top>376</top>
		<width>7</width>
		<height>7</height>
		<id>86</id>
		<name>byl_hran</name>
		<comment></comment>
	</relation>
	<relation>
		<left>700</left>
		<top>332</top>
		<width>7</width>
		<height>7</height>
		<id>14</id>
		<name>hral</name>
		<comment></comment>
	</relation>
	<relation>
		<left>686</left>
		<top>231</top>
		<width>7</width>
		<height>7</height>
		<id>58</id>
		<name>je_druhu</name>
		<comment></comment>
	</relation>
</schema>
