<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ER Modeller version 4.0 schema -->
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,notation,comment,usertype*,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT usertype (typename, datatypedef)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT typename (#PCDATA)>
<!ELEMENT datatypedef (datatype, item*)>
<!ELEMENT item (itemname, datatype)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>148</id>
	<name>Schema</name>
	<notation>2</notation>
	<comment></comment>
	<relation>
		<left>428</left>
		<top>585</top>
		<width>7</width>
		<height>7</height>
		<id>139</id>
		<name>Rel13</name>
		<comment></comment>
	</relation>
	<entity>
		<left>241</left>
		<top>408</top>
		<width>184</width>
		<height>119</height>
		<id>116</id>
		<name>rozhodci</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>246</left>
		<top>438</top>
		<width>54</width>
		<height>13</height>
		<id>122</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>116</ent>
	</atribute>
	<atribute>
		<left>246</left>
		<top>458</top>
		<width>64</width>
		<height>13</height>
		<id>123</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>116</ent>
	</atribute>
	<atribute>
		<left>246</left>
		<top>478</top>
		<width>44</width>
		<height>13</height>
		<id>124</id>
		<name>level</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>116</ent>
	</atribute>
	<atribute>
		<left>246</left>
		<top>498</top>
		<width>51</width>
		<height>13</height>
		<id>145</id>
		<name>hlavni</name>
		<comment></comment>
		<datatype>VarChar2(1)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>116</ent>
	</atribute>
	<cardinality>
		<left>425</left>
		<top>413</top>
		<width>56</width>
		<height>29</height>
		<id>119</id>
		<name>je_rizen</name>
		<comment></comment>
		<ent>116</ent>
		<rel>117</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>465</left>
		<top>446</top>
		<width>7</width>
		<height>7</height>
		<id>117</id>
		<name>Rel11</name>
		<comment></comment>
	</relation>
	<entity>
		<left>252</left>
		<top>603</top>
		<width>200</width>
		<height>80</height>
		<id>138</id>
		<name>system</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>257</left>
		<top>633</top>
		<width>50</width>
		<height>13</height>
		<id>142</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>138</ent>
	</atribute>
	<atribute>
		<left>257</left>
		<top>653</top>
		<width>50</width>
		<height>13</height>
		<id>143</id>
		<name>popis</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>138</ent>
	</atribute>
	<cardinality>
		<left>324</left>
		<top>575</top>
		<width>44</width>
		<height>29</height>
		<id>140</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>138</ent>
		<rel>139</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>766</left>
		<top>635</top>
		<width>7</width>
		<height>7</height>
		<id>95</id>
		<name>Rel7</name>
		<comment></comment>
	</relation>
	<entity>
		<left>504</left>
		<top>423</top>
		<width>227</width>
		<height>219</height>
		<id>36</id>
		<name>turnaj</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>509</left>
		<top>533</top>
		<width>105</width>
		<height>13</height>
		<id>51</id>
		<name>pocet ucastniku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>5</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>493</top>
		<width>50</width>
		<height>13</height>
		<id>49</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>3</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>473</top>
		<width>54</width>
		<height>13</height>
		<id>38</id>
		<name>datum</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>553</top>
		<width>110</width>
		<height>13</height>
		<id>121</id>
		<name>dolarova_dotace</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>6</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>453</top>
		<width>94</width>
		<height>13</height>
		<id>37</id>
		<name>misto_konani</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>573</top>
		<width>83</width>
		<height>13</height>
		<id>133</id>
		<name>jina_dotace</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>7</position>
		<ent>36</ent>
	</atribute>
	<cardinality>
		<left>592</left>
		<top>395</top>
		<width>39</width>
		<height>29</height>
		<id>82</id>
		<name>deck</name>
		<comment></comment>
		<ent>36</ent>
		<rel>81</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>448</left>
		<top>581</top>
		<width>56</width>
		<height>29</height>
		<id>141</id>
		<name>Entity15</name>
		<comment></comment>
		<ent>36</ent>
		<rel>139</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>470</left>
		<top>452</top>
		<width>34</width>
		<height>29</height>
		<id>118</id>
		<name>ridi</name>
		<comment></comment>
		<ent>36</ent>
		<rel>117</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<atribute>
		<left>509</left>
		<top>513</top>
		<width>54</width>
		<height>13</height>
		<id>50</id>
		<name>format</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>593</top>
		<width>43</width>
		<height>13</height>
		<id>144</id>
		<name>top8</name>
		<comment></comment>
		<datatype>VarChar2(1)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>8</position>
		<ent>36</ent>
	</atribute>
	<atribute>
		<left>509</left>
		<top>613</top>
		<width>62</width>
		<height>13</height>
		<id>147</id>
		<name>vstupne</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>9</position>
		<ent>36</ent>
	</atribute>
	<cardinality>
		<left>731</left>
		<top>593</top>
		<width>36</width>
		<height>29</height>
		<id>96</id>
		<name>kolo</name>
		<comment></comment>
		<ent>36</ent>
		<rel>95</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>698</left>
		<top>733</top>
		<width>7</width>
		<height>7</height>
		<id>101</id>
		<name>Rel8</name>
		<comment></comment>
	</relation>
	<relation>
		<left>639</left>
		<top>408</top>
		<width>7</width>
		<height>7</height>
		<id>81</id>
		<name>byl_hran</name>
		<comment></comment>
	</relation>
	<relation>
		<left>498</left>
		<top>299</top>
		<width>7</width>
		<height>7</height>
		<id>9</id>
		<name>hral</name>
		<comment></comment>
	</relation>
	<entity>
		<left>226</left>
		<top>247</top>
		<width>197</width>
		<height>130</height>
		<id>8</id>
		<name>osoba</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>231</left>
		<top>277</top>
		<width>29</width>
		<height>13</height>
		<id>91</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>8</ent>
	</atribute>
	<atribute>
		<left>231</left>
		<top>297</top>
		<width>54</width>
		<height>13</height>
		<id>92</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>8</ent>
	</atribute>
	<atribute>
		<left>231</left>
		<top>317</top>
		<width>64</width>
		<height>13</height>
		<id>93</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>8</ent>
	</atribute>
	<cardinality>
		<left>423</left>
		<top>308</top>
		<width>56</width>
		<height>29</height>
		<id>10</id>
		<name>byl hran</name>
		<comment></comment>
		<ent>8</ent>
		<rel>9</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>763</left>
		<top>713</top>
		<width>200</width>
		<height>79</height>
		<id>94</id>
		<name>kolo</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>768</left>
		<top>743</top>
		<width>45</width>
		<height>13</height>
		<id>98</id>
		<name>cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>94</ent>
	</atribute>
	<atribute>
		<left>768</left>
		<top>763</top>
		<width>74</width>
		<height>13</height>
		<id>99</id>
		<name>id_turnaje</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>94</ent>
	</atribute>
	<cardinality>
		<left>717</left>
		<top>747</top>
		<width>46</width>
		<height>29</height>
		<id>103</id>
		<name>zapas</name>
		<comment></comment>
		<ent>94</ent>
		<rel>101</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>780</left>
		<top>685</top>
		<width>44</width>
		<height>29</height>
		<id>97</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>94</ent>
		<rel>95</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>1000</left>
		<top>682</top>
		<width>183</width>
		<height>59</height>
		<id>42</id>
		<name>typ</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>1005</left>
		<top>712</top>
		<width>50</width>
		<height>13</height>
		<id>46</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>42</ent>
	</atribute>
	<cardinality>
		<left>1073</left>
		<top>654</top>
		<width>34</width>
		<height>29</height>
		<id>45</id>
		<name></name>
		<comment></comment>
		<ent>42</ent>
		<rel>43</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>1059</left>
		<top>596</top>
		<width>7</width>
		<height>7</height>
		<id>43</id>
		<name>ma_typ</name>
		<comment></comment>
	</relation>
	<entity>
		<left>969</left>
		<top>438</top>
		<width>222</width>
		<height>119</height>
		<id>14</id>
		<name>MTG_karta</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>974</left>
		<top>488</top>
		<width>54</width>
		<height>13</height>
		<id>47</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>14</ent>
	</atribute>
	<atribute>
		<left>974</left>
		<top>508</top>
		<width>107</width>
		<height>13</height>
		<id>76</id>
		<name>md_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>14</ent>
	</atribute>
	<cardinality>
		<left>927</left>
		<top>452</top>
		<width>43</width>
		<height>29</height>
		<id>26</id>
		<name>barva</name>
		<comment></comment>
		<ent>14</ent>
		<rel>25</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>981</left>
		<top>410</top>
		<width>65</width>
		<height>29</height>
		<id>79</id>
		<name>obsahuje</name>
		<comment></comment>
		<ent>14</ent>
		<rel>18</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1035</left>
		<top>557</top>
		<width>34</width>
		<height>29</height>
		<id>44</id>
		<name></name>
		<comment></comment>
		<ent>14</ent>
		<rel>43</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<atribute>
		<left>974</left>
		<top>468</top>
		<width>89</width>
		<height>13</height>
		<id>22</id>
		<name>casting_cost</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>14</ent>
	</atribute>
	<atribute>
		<left>974</left>
		<top>528</top>
		<width>103</width>
		<height>13</height>
		<id>78</id>
		<name>sb_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>14</ent>
	</atribute>
	<entity>
		<left>802</left>
		<top>250</top>
		<width>187</width>
		<height>99</height>
		<id>7</id>
		<name>Deck</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>807</left>
		<top>280</top>
		<width>29</width>
		<height>13</height>
		<id>48</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>7</ent>
	</atribute>
	<atribute>
		<left>807</left>
		<top>320</top>
		<width>47</width>
		<height>13</height>
		<id>132</id>
		<name>barvy</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>7</ent>
	</atribute>
	<atribute>
		<left>807</left>
		<top>300</top>
		<width>54</width>
		<height>13</height>
		<id>131</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>7</ent>
	</atribute>
	<cardinality>
		<left>870</left>
		<top>222</top>
		<width>38</width>
		<height>29</height>
		<id>54</id>
		<name>druh</name>
		<comment></comment>
		<ent>7</ent>
		<rel>53</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>847</left>
		<top>349</top>
		<width>68</width>
		<height>29</height>
		<id>83</id>
		<name>na_turnaji</name>
		<comment></comment>
		<ent>7</ent>
		<rel>81</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>989</left>
		<top>274</top>
		<width>72</width>
		<height>29</height>
		<id>19</id>
		<name>MTG_karta</name>
		<comment></comment>
		<ent>7</ent>
		<rel>18</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>762</left>
		<top>283</top>
		<width>41</width>
		<height>29</height>
		<id>11</id>
		<name>hrala</name>
		<comment></comment>
		<ent>7</ent>
		<rel>9</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>1054</left>
		<top>387</top>
		<width>7</width>
		<height>7</height>
		<id>18</id>
		<name>obsahuje</name>
		<comment></comment>
	</relation>
	<relation>
		<left>822</left>
		<top>231</top>
		<width>7</width>
		<height>7</height>
		<id>53</id>
		<name>je_druhu</name>
		<comment></comment>
	</relation>
	<entity>
		<left>475</left>
		<top>209</top>
		<width>183</width>
		<height>59</height>
		<id>52</id>
		<name>druh</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>480</left>
		<top>239</top>
		<width>50</width>
		<height>13</height>
		<id>56</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>52</ent>
	</atribute>
	<cardinality>
		<left>658</left>
		<top>218</top>
		<width>41</width>
		<height>29</height>
		<id>55</id>
		<name>Deck</name>
		<comment></comment>
		<ent>52</ent>
		<rel>53</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<relation>
		<left>340</left>
		<top>699</top>
		<width>7</width>
		<height>7</height>
		<id>127</id>
		<name>Rel12</name>
		<comment></comment>
	</relation>
	<entity>
		<left>196</left>
		<top>737</top>
		<width>228</width>
		<height>79</height>
		<id>125</id>
		<name>vysledek</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>201</left>
		<top>787</top>
		<width>120</width>
		<height>13</height>
		<id>130</id>
		<name>hrac_2_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>125</ent>
	</atribute>
	<cardinality>
		<left>244</left>
		<top>709</top>
		<width>46</width>
		<height>29</height>
		<id>129</id>
		<name>zapas</name>
		<comment></comment>
		<ent>125</ent>
		<rel>127</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<atribute>
		<left>201</left>
		<top>767</top>
		<width>120</width>
		<height>13</height>
		<id>126</id>
		<name>hrac_1_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>125</ent>
	</atribute>
	<entity>
		<left>452</left>
		<top>695</top>
		<width>207</width>
		<height>119</height>
		<id>100</id>
		<name>zapas</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>457</left>
		<top>745</top>
		<width>57</width>
		<height>13</height>
		<id>105</id>
		<name>hrac_2</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>100</ent>
	</atribute>
	<atribute>
		<left>457</left>
		<top>725</top>
		<width>57</width>
		<height>13</height>
		<id>104</id>
		<name>hrac_1</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>100</ent>
	</atribute>
	<atribute>
		<left>457</left>
		<top>765</top>
		<width>74</width>
		<height>13</height>
		<id>134</id>
		<name>poznamky</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>100</ent>
	</atribute>
	<atribute>
		<left>457</left>
		<top>785</top>
		<width>38</width>
		<height>13</height>
		<id>135</id>
		<name>bye</name>
		<comment></comment>
		<datatype>Char(1)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>100</ent>
	</atribute>
	<cardinality>
		<left>659</left>
		<top>714</top>
		<width>36</width>
		<height>29</height>
		<id>102</id>
		<name>kolo</name>
		<comment></comment>
		<ent>100</ent>
		<rel>101</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>392</left>
		<top>695</top>
		<width>60</width>
		<height>29</height>
		<id>128</id>
		<name>vysledek</name>
		<comment></comment>
		<ent>100</ent>
		<rel>127</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>831</left>
		<top>571</top>
		<width>127</width>
		<height>59</height>
		<id>24</id>
		<name>barva</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>836</left>
		<top>601</top>
		<width>50</width>
		<height>13</height>
		<id>40</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>24</ent>
	</atribute>
	<cardinality>
		<left>862</left>
		<top>543</top>
		<width>64</width>
		<height>29</height>
		<id>27</id>
		<name>ma barvu</name>
		<comment></comment>
		<ent>24</ent>
		<rel>25</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<relation>
		<left>914</left>
		<top>509</top>
		<width>7</width>
		<height>7</height>
		<id>25</id>
		<name>je_barvy</name>
		<comment></comment>
	</relation>
</schema>
