<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ER Modeller version 4.0 schema -->
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,notation,comment,usertype*,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT usertype (typename, datatypedef)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT typename (#PCDATA)>
<!ELEMENT datatypedef (datatype, item*)>
<!ELEMENT item (itemname, datatype)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>164</id>
	<name>Schema</name>
	<notation>2</notation>
	<comment></comment>
	<entity>
		<left>1083</left>
		<top>497</top>
		<width>127</width>
		<height>79</height>
		<id>27</id>
		<name>barva</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>1088</left>
		<top>547</top>
		<width>29</width>
		<height>13</height>
		<id>157</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>27</ent>
	</atribute>
	<atribute>
		<left>1088</left>
		<top>527</top>
		<width>50</width>
		<height>13</height>
		<id>43</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>27</ent>
	</atribute>
	<cardinality>
		<left>1114</left>
		<top>469</top>
		<width>64</width>
		<height>29</height>
		<id>30</id>
		<name>ma barvu</name>
		<comment></comment>
		<ent>27</ent>
		<rel>28</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>180</left>
		<top>596</top>
		<width>200</width>
		<height>99</height>
		<id>141</id>
		<name>system</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>185</left>
		<top>646</top>
		<width>50</width>
		<height>13</height>
		<id>146</id>
		<name>popis</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>141</ent>
	</atribute>
	<atribute>
		<left>185</left>
		<top>626</top>
		<width>50</width>
		<height>13</height>
		<id>145</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>141</ent>
	</atribute>
	<atribute>
		<left>185</left>
		<top>666</top>
		<width>29</width>
		<height>13</height>
		<id>154</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>3</position>
		<ent>141</ent>
	</atribute>
	<cardinality>
		<left>252</left>
		<top>568</top>
		<width>44</width>
		<height>29</height>
		<id>143</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>141</ent>
		<rel>142</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>923</left>
		<top>592</top>
		<width>267</width>
		<height>79</height>
		<id>97</id>
		<name>kolo</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>928</left>
		<top>622</top>
		<width>45</width>
		<height>13</height>
		<id>101</id>
		<name>cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>97</ent>
	</atribute>
	<cardinality>
		<left>879</left>
		<top>613</top>
		<width>44</width>
		<height>29</height>
		<id>100</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>97</ent>
		<rel>98</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>1000</left>
		<top>671</top>
		<width>46</width>
		<height>29</height>
		<id>106</id>
		<name>zapas</name>
		<comment></comment>
		<ent>97</ent>
		<rel>104</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>197</left>
		<top>419</top>
		<width>184</width>
		<height>139</height>
		<id>119</id>
		<name>rozhodci</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>202</left>
		<top>509</top>
		<width>51</width>
		<height>13</height>
		<id>148</id>
		<name>hlavni</name>
		<comment></comment>
		<datatype>VarChar2(1)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>119</ent>
	</atribute>
	<atribute>
		<left>202</left>
		<top>449</top>
		<width>54</width>
		<height>13</height>
		<id>125</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>119</ent>
	</atribute>
	<atribute>
		<left>202</left>
		<top>489</top>
		<width>44</width>
		<height>13</height>
		<id>127</id>
		<name>level</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>119</ent>
	</atribute>
	<atribute>
		<left>202</left>
		<top>469</top>
		<width>64</width>
		<height>13</height>
		<id>126</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>119</ent>
	</atribute>
	<atribute>
		<left>202</left>
		<top>529</top>
		<width>29</width>
		<height>13</height>
		<id>156</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>5</position>
		<ent>119</ent>
	</atribute>
	<cardinality>
		<left>381</left>
		<top>424</top>
		<width>56</width>
		<height>29</height>
		<id>122</id>
		<name>je_rizen</name>
		<comment></comment>
		<ent>119</ent>
		<rel>120</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>860</left>
		<top>498</top>
		<width>183</width>
		<height>79</height>
		<id>45</id>
		<name>typ</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>865</left>
		<top>528</top>
		<width>50</width>
		<height>13</height>
		<id>49</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>45</ent>
	</atribute>
	<atribute>
		<left>865</left>
		<top>548</top>
		<width>29</width>
		<height>13</height>
		<id>151</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>45</ent>
	</atribute>
	<cardinality>
		<left>933</left>
		<top>470</top>
		<width>34</width>
		<height>29</height>
		<id>48</id>
		<name></name>
		<comment></comment>
		<ent>45</ent>
		<rel>46</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>939</left>
		<top>713</top>
		<width>207</width>
		<height>119</height>
		<id>103</id>
		<name>zapas</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>944</left>
		<top>763</top>
		<width>57</width>
		<height>13</height>
		<id>108</id>
		<name>hrac_2</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>103</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>743</top>
		<width>57</width>
		<height>13</height>
		<id>107</id>
		<name>hrac_1</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>103</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>783</top>
		<width>74</width>
		<height>13</height>
		<id>137</id>
		<name>poznamky</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>103</ent>
	</atribute>
	<atribute>
		<left>944</left>
		<top>803</top>
		<width>38</width>
		<height>13</height>
		<id>138</id>
		<name>bye</name>
		<comment></comment>
		<datatype>Char(1)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>103</ent>
	</atribute>
	<cardinality>
		<left>1146</left>
		<top>732</top>
		<width>36</width>
		<height>29</height>
		<id>105</id>
		<name>kolo</name>
		<comment></comment>
		<ent>103</ent>
		<rel>104</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>879</left>
		<top>713</top>
		<width>60</width>
		<height>29</height>
		<id>131</id>
		<name>vysledek</name>
		<comment></comment>
		<ent>103</ent>
		<rel>130</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>705</left>
		<top>747</top>
		<width>228</width>
		<height>79</height>
		<id>128</id>
		<name>vysledek</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>710</left>
		<top>797</top>
		<width>120</width>
		<height>13</height>
		<id>133</id>
		<name>hrac_2_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>128</ent>
	</atribute>
	<atribute>
		<left>710</left>
		<top>777</top>
		<width>120</width>
		<height>13</height>
		<id>129</id>
		<name>hrac_1_vyhral_her</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>128</ent>
	</atribute>
	<cardinality>
		<left>753</left>
		<top>719</top>
		<width>46</width>
		<height>29</height>
		<id>132</id>
		<name>zapas</name>
		<comment></comment>
		<ent>128</ent>
		<rel>130</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>997</left>
		<top>321</top>
		<width>222</width>
		<height>139</height>
		<id>17</id>
		<name>MTG_karta</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>1002</left>
		<top>351</top>
		<width>89</width>
		<height>13</height>
		<id>25</id>
		<name>casting_cost</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>17</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>411</top>
		<width>103</width>
		<height>13</height>
		<id>81</id>
		<name>sb_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>17</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>371</top>
		<width>54</width>
		<height>13</height>
		<id>50</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>17</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>431</top>
		<width>29</width>
		<height>13</height>
		<id>152</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>5</position>
		<ent>17</ent>
	</atribute>
	<atribute>
		<left>1002</left>
		<top>391</top>
		<width>107</width>
		<height>13</height>
		<id>79</id>
		<name>md_pocet_kopii</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>17</ent>
	</atribute>
	<cardinality>
		<left>1111</left>
		<top>460</top>
		<width>34</width>
		<height>29</height>
		<id>47</id>
		<name></name>
		<comment></comment>
		<ent>17</ent>
		<rel>46</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1092</left>
		<top>293</top>
		<width>65</width>
		<height>29</height>
		<id>82</id>
		<name>obsahuje</name>
		<comment></comment>
		<ent>17</ent>
		<rel>21</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>1219</left>
		<top>344</top>
		<width>43</width>
		<height>29</height>
		<id>29</id>
		<name>barva</name>
		<comment></comment>
		<ent>17</ent>
		<rel>28</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>780</left>
		<top>261</top>
		<width>187</width>
		<height>99</height>
		<id>10</id>
		<name>Deck</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>785</left>
		<top>291</top>
		<width>29</width>
		<height>13</height>
		<id>51</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>10</ent>
	</atribute>
	<atribute>
		<left>785</left>
		<top>311</top>
		<width>54</width>
		<height>13</height>
		<id>134</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>10</ent>
	</atribute>
	<atribute>
		<left>785</left>
		<top>331</top>
		<width>47</width>
		<height>13</height>
		<id>135</id>
		<name>barvy</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>10</ent>
	</atribute>
	<cardinality>
		<left>967</left>
		<top>285</top>
		<width>72</width>
		<height>29</height>
		<id>22</id>
		<name>MTG_karta</name>
		<comment></comment>
		<ent>10</ent>
		<rel>21</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>810</left>
		<top>233</top>
		<width>38</width>
		<height>29</height>
		<id>57</id>
		<name>druh</name>
		<comment></comment>
		<ent>10</ent>
		<rel>56</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>825</left>
		<top>360</top>
		<width>68</width>
		<height>29</height>
		<id>86</id>
		<name>na_turnaji</name>
		<comment></comment>
		<ent>10</ent>
		<rel>84</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>740</left>
		<top>323</top>
		<width>41</width>
		<height>29</height>
		<id>14</id>
		<name>hrala</name>
		<comment></comment>
		<ent>10</ent>
		<rel>12</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>193</left>
		<top>233</top>
		<width>183</width>
		<height>79</height>
		<id>55</id>
		<name>druh</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>198</left>
		<top>283</top>
		<width>29</width>
		<height>13</height>
		<id>155</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>2</position>
		<ent>55</ent>
	</atribute>
	<atribute>
		<left>198</left>
		<top>263</top>
		<width>50</width>
		<height>13</height>
		<id>59</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>55</ent>
	</atribute>
	<cardinality>
		<left>376</left>
		<top>238</top>
		<width>41</width>
		<height>29</height>
		<id>58</id>
		<name>Deck</name>
		<comment></comment>
		<ent>55</ent>
		<rel>56</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>394</left>
		<top>703</top>
		<width>183</width>
		<height>133</height>
		<id>158</id>
		<name>format</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>399</left>
		<top>733</top>
		<width>29</width>
		<height>13</height>
		<id>159</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>158</ent>
	</atribute>
	<atribute>
		<left>399</left>
		<top>753</top>
		<width>50</width>
		<height>13</height>
		<id>160</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>158</ent>
	</atribute>
	<cardinality>
		<left>487</left>
		<top>675</top>
		<width>44</width>
		<height>29</height>
		<id>162</id>
		<name>turnaj</name>
		<comment></comment>
		<ent>158</ent>
		<rel>161</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>425</left>
		<top>264</top>
		<width>197</width>
		<height>130</height>
		<id>11</id>
		<name>osoba</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>430</left>
		<top>294</top>
		<width>29</width>
		<height>13</height>
		<id>94</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>11</ent>
	</atribute>
	<atribute>
		<left>430</left>
		<top>314</top>
		<width>54</width>
		<height>13</height>
		<id>95</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>11</ent>
	</atribute>
	<atribute>
		<left>430</left>
		<top>334</top>
		<width>64</width>
		<height>13</height>
		<id>96</id>
		<name>prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>11</ent>
	</atribute>
	<cardinality>
		<left>622</left>
		<top>325</top>
		<width>56</width>
		<height>29</height>
		<id>13</id>
		<name>byl hran</name>
		<comment></comment>
		<ent>11</ent>
		<rel>12</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>465</left>
		<top>446</top>
		<width>7</width>
		<height>7</height>
		<id>120</id>
		<name>Rel11</name>
		<comment></comment>
	</relation>
	<relation>
		<left>378</left>
		<top>566</top>
		<width>7</width>
		<height>7</height>
		<id>142</id>
		<name>Rel13</name>
		<comment></comment>
	</relation>
	<relation>
		<left>830</left>
		<top>583</top>
		<width>7</width>
		<height>7</height>
		<id>98</id>
		<name>Rel7</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1171</left>
		<top>690</top>
		<width>7</width>
		<height>7</height>
		<id>104</id>
		<name>Rel8</name>
		<comment></comment>
	</relation>
	<relation>
		<left>872</left>
		<top>683</top>
		<width>7</width>
		<height>7</height>
		<id>130</id>
		<name>Rel12</name>
		<comment></comment>
	</relation>
	<relation>
		<left>563</left>
		<top>675</top>
		<width>7</width>
		<height>7</height>
		<id>161</id>
		<name>Rel12</name>
		<comment></comment>
	</relation>
	<relation>
		<left>680</left>
		<top>378</top>
		<width>7</width>
		<height>7</height>
		<id>84</id>
		<name>byl_hran</name>
		<comment></comment>
	</relation>
	<relation>
		<left>686</left>
		<top>230</top>
		<width>7</width>
		<height>7</height>
		<id>56</id>
		<name>je_druhu</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1222</left>
		<top>461</top>
		<width>7</width>
		<height>7</height>
		<id>28</id>
		<name>je_barvy</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1010</left>
		<top>479</top>
		<width>7</width>
		<height>7</height>
		<id>46</id>
		<name>ma_typ</name>
		<comment></comment>
	</relation>
	<relation>
		<left>1050</left>
		<top>299</top>
		<width>7</width>
		<height>7</height>
		<id>21</id>
		<name>obsahuje</name>
		<comment></comment>
	</relation>
	<relation>
		<left>701</left>
		<top>331</top>
		<width>7</width>
		<height>7</height>
		<id>12</id>
		<name>hral</name>
		<comment></comment>
	</relation>
	<entity>
		<left>539</left>
		<top>404</top>
		<width>227</width>
		<height>239</height>
		<id>39</id>
		<name>turnaj</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>544</left>
		<top>514</top>
		<width>110</width>
		<height>13</height>
		<id>124</id>
		<name>dolarova_dotace</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>5</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>534</top>
		<width>83</width>
		<height>13</height>
		<id>136</id>
		<name>jina_dotace</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>6</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>574</top>
		<width>62</width>
		<height>13</height>
		<id>150</id>
		<name>vstupne</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>8</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>434</top>
		<width>94</width>
		<height>13</height>
		<id>40</id>
		<name>misto_konani</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>454</top>
		<width>54</width>
		<height>13</height>
		<id>41</id>
		<name>datum</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>474</top>
		<width>50</width>
		<height>13</height>
		<id>52</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>3</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>594</top>
		<width>29</width>
		<height>13</height>
		<id>153</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>9</position>
		<ent>39</ent>
	</atribute>
	<atribute>
		<left>544</left>
		<top>554</top>
		<width>43</width>
		<height>13</height>
		<id>147</id>
		<name>top8</name>
		<comment>popisuje, jestli ma turnaj TOP 8</comment>
		<datatype>VarChar2(1)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>7</position>
		<ent>39</ent>
	</atribute>
	<cardinality>
		<left>505</left>
		<top>433</top>
		<width>34</width>
		<height>29</height>
		<id>121</id>
		<name>ridi</name>
		<comment></comment>
		<ent>39</ent>
		<rel>120</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>766</left>
		<top>574</top>
		<width>36</width>
		<height>29</height>
		<id>99</id>
		<name>kolo</name>
		<comment></comment>
		<ent>39</ent>
		<rel>98</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>483</left>
		<top>562</top>
		<width>56</width>
		<height>29</height>
		<id>144</id>
		<name>Entity15</name>
		<comment></comment>
		<ent>39</ent>
		<rel>142</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>627</left>
		<top>376</top>
		<width>39</width>
		<height>29</height>
		<id>85</id>
		<name>deck</name>
		<comment></comment>
		<ent>39</ent>
		<rel>84</rel>
		<arbitrary>true</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>648</left>
		<top>643</top>
		<width>48</width>
		<height>29</height>
		<id>163</id>
		<name>format</name>
		<comment></comment>
		<ent>39</ent>
		<rel>161</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<atribute>
		<left>544</left>
		<top>494</top>
		<width>109</width>
		<height>13</height>
		<id>54</id>
		<name>pocet_ucastniku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>4</position>
		<ent>39</ent>
	</atribute>
</schema>
