=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/michal_pavlasek_y36xml/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tv_program (vysilani*, porad*, clovek*, verze) >
    <!ELEMENT vysilani (kanal, zacatek, konec, co) >
        <!ELEMENT kanal (#PCDATA) >
        <!ELEMENT zacatek (#PCDATA) >
        <!ELEMENT konec (#PCDATA) >
        <!ELEMENT co EMPTY >
            <!ATTLIST co ref IDREF #REQUIRED >
    <!ELEMENT porad (nazev, typ, popis, herci*, reziser?, delka) >
        <!ATTLIST porad id_poradu ID #REQUIRED >
        <!ELEMENT nazev (#PCDATA) >
        <!ELEMENT typ (#PCDATA) >
        <!ELEMENT popis (#PCDATA) >
        <!ELEMENT herci EMPTY >
            <!ATTLIST herci ref IDREF #REQUIRED >
        <!ELEMENT reziser EMPTY >
            <!ATTLIST reziser ref IDREF #REQUIRED >
        <!ELEMENT delka (#PCDATA) >
    <!ELEMENT clovek (jmeno, prijmeni) >
        <!ATTLIST clovek id_cloveka ID #REQUIRED >
        <!ELEMENT jmeno (#PCDATA) >
        <!ELEMENT prijmeni (#PCDATA) >
     <!ELEMENT verze (#PCDATA) >

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/michal_pavlasek_y36xml/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><?xml-stylesheet type="text/xsl" href="data2html.xsl"?>
<tv_program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd">

 <!-- <!DOCTYPE tv_program SYSTEM "data.dtd">
<tv_program> --> 
    
    <!-- vysilani - cas a odkaz na porad -->
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T10:00:00</zacatek>
        <konec>2007-12-24T11:10:00</konec>
        <co ref="obusku"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T11:10:00</zacatek>
        <konec>2007-12-24T12:00:00</konec>
        <co ref="p0001"/>
    </vysilani>        
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T12:00:00</zacatek>
        <konec>2007-12-24T13:00:00</konec>
        <co ref="p0002"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T15:25:00</zacatek>
        <konec>2007-12-24T17:15:00</konec>
        <co ref="byljednou"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T19:00:00</zacatek>
        <konec>2007-12-24T20:20:00</konec>
        <co ref="zivoty"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-24T21:05:00</zacatek>
        <konec>2007-12-24T22:05:00</konec>
        <co ref="hrab17"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT2</kanal>
        <zacatek>2007-12-24T13:25:00</zacatek>
        <konec>2007-12-24T15:05:00</konec>
        <co ref="afr_kralovna"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT2</kanal>
        <zacatek>2007-12-24T16:45:00</zacatek>
        <konec>2007-12-24T17:45:00</konec>
        <co ref="vanpribeh"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T11:15:00</zacatek>
        <konec>2007-12-24T12:45:00</konec>
        <co ref="pysna"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T12:45:00</zacatek>
        <konec>2007-12-24T14:10:00</konec>
        <co ref="lyznici"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T15:55:00</zacatek>
        <konec>2007-12-24T17:30:00</konec>
        <co ref="princezny"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T17:40:00</zacatek>
        <konec>2007-12-24T18:35:00</konec>
        <co ref="ulice694"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T18:35:00</zacatek>
        <konec>2007-12-24T20:00:00</konec>
        <co ref="popelka"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T20:00:00</zacatek>
        <konec>2007-12-24T20:30:00</konec>
        <co ref="shrek"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-24T20:30:00</zacatek>
        <konec>2007-12-24T22:15:00</konec>
        <co ref="prosit"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-25T10:00:00</zacatek>
        <konec>2007-12-25T11:30:00</konec>
        <co ref="rumpl"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-25T13:00:00</zacatek>
        <konec>2007-12-25T14:00:00</konec>
        <co ref="chleba"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-25T15:25:00</zacatek>
        <konec>2007-12-25T16:55:00</konec>
        <co ref="prednosta"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-25T18:05:00</zacatek>
        <konec>2007-12-25T18:45:00</konec>
        <co ref="honza"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT1</kanal>
        <zacatek>2007-12-25T20:00:00</zacatek>
        <konec>2007-12-25T21:15:00</konec>
        <co ref="srdce"/>
    </vysilani>
    
    <vysilani>
        <kanal>CT2</kanal>
        <zacatek>2007-12-25T10:00:00</zacatek>
        <konec>2007-12-25T11:00:00</konec>
        <co ref="sluzba"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-25T10:45:00</zacatek>
        <konec>2007-12-25T12:10:00</konec>
        <co ref="kovar"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-25T12:10:00</zacatek>
        <konec>2007-12-25T13:40:00</konec>
        <co ref="eva"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-25T13:40:00</zacatek>
        <konec>2007-12-25T15:15:00</konec>
        <co ref="kovboj"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-25T15:15:00</zacatek>
        <konec>2007-12-25T17:05:00</konec>
        <co ref="samdoma"/>
    </vysilani>
    
    <vysilani>
        <kanal>nova</kanal>
        <zacatek>2007-12-25T17:05:00</zacatek>
        <konec>2007-12-25T18:35:00</konec>
        <co ref="jasnenka"/>
    </vysilani>                
        
    <!-- porady -->    
    <porad id_poradu="obusku">
        <nazev>Obusku z pytle ven</nazev>
        <typ>film</typ>        
        <popis>pohadka 1955</popis>
        
        <reziser ref="pleskot"/>
        <delka>70</delka>
    </porad>           
    
    <porad id_poradu="p0001">
        <nazev>Na Vanoce</nazev>
        <typ>publicistika</typ>
        <popis>nejaka vanocni ptakovina</popis>
        <delka>50</delka>
    </porad>   
    
    <porad id_poradu="p0002">
        <nazev>Jednou v roce na vanoce</nazev>
        <typ>publicistika</typ>
        <popis>nejaka vanocni blbost</popis>
        <delka>60</delka>
    </porad>
    
    <porad id_poradu="byljednou">
        <nazev>Byl jednou jeden kral</nazev>
        <typ>film</typ>
        <popis>pohadka 1954</popis>
        <herci ref="werich"/>
        <herci ref="burian"/>
        <reziser ref="zemanb"/>
        <delka>110</delka>
    </porad>
    
    <porad id_poradu="zivoty">
        <nazev>Tri zivoty</nazev>
        <typ>film</typ>
        <popis>pohadka 2007</popis>
        <herci ref="molnarl"/>
        <herci ref="molnarp"/>
        <reziser ref="strach"/>
        <delka>80</delka>
    </porad>
    
    <porad id_poradu="hrab17">
        <nazev>Hrabenky 17/17</nazev>
        <typ>serial</typ>
        <popis>dementni serial pro nase maminky</popis>
        <herci ref="langmajer"/>
        <reziser ref="brabec"/>
        <delka>60</delka>
    </porad>
    
    <porad id_poradu="afr_kralovna">
        <nazev>Africka Kralovna</nazev>
        <typ>film</typ>
        <popis>usmevny pribeh</popis>
        <herci ref="hepburn"/>
        <herci ref="bogart"/>
        <reziser ref="huston"/>        
        <delka>90</delka>
    </porad>
    
    <porad id_poradu="lyznici">
        <nazev>Krakonos a lyznici</nazev>
        <typ>film</typ>
        <popis>rodinny film 1980</popis>
        <delka>85</delka>
    </porad>
    
    <porad id_poradu="princezny">
        <nazev>Jak se budi princezny</nazev>
        <typ>film</typ>
        <popis>pohadka 1977</popis>
        <herci ref="hruska"/>
        <herci ref="dvorska"/>
        <herci ref="mensik"/>
        <reziser ref="vorel"/>
        <delka>95</delka>
    </porad>
            
   <porad id_poradu="pysna">
        <nazev>Pysna princezna</nazev>
        <typ>film</typ>
        <popis>pohadka 1952</popis>
       <herci ref="vraz"/>
       <herci ref="vrana"/>
       <reziser ref="zemanb"/>       
        <delka>90</delka>
    </porad>
        
    <porad id_poradu="vanpribeh">
        <nazev>Vanocni pribeh</nazev>
        <typ>film</typ>
        <popis>film 2007</popis>
        <delka>60</delka>
    </porad>            
    
    <porad id_poradu="ulice694">
        <nazev>Ulice 694</nazev>
        <typ>serial</typ>
        <popis>dementni serial tv nova</popis>
        <delka>55</delka>
    </porad>
    
    <porad id_poradu="popelka">
        <nazev>Tri orisky pro popelku</nazev>
        <typ>film</typ>
        <popis>pohadka 1973</popis>
        <herci ref="safr"/>
        <herci ref="travn"/>
        <reziser ref="vorel"/>
        <delka>85</delka>
    </porad>
    
    <porad id_poradu="shrek">
        <nazev>Shrekoleda</nazev>
        <typ>film</typ>
        <popis>Animovana pohadka 2007</popis>
        <delka>30</delka>
    </porad>
    
    <porad id_poradu="prosit">
        <nazev>Smim prosit?</nazev>
        <typ>film</typ>
        <popis>romanticka komedie 2004</popis>
        <reziser ref="gere"/>
        <delka>105</delka>
    </porad>
    
    <porad id_poradu="rumpl">
        <nazev>RumplCimprCampr</nazev>
        <typ>film</typ>
        <popis>pohadka 1997</popis>
        <herci ref="werich"/>
        <herci ref="potm"/>
        <reziser ref="werich"/>
        <delka>90</delka>
    </porad>
    
    <porad id_poradu="chleba">
        <nazev>O divce, ktera slapla na chleb</nazev>
        <typ>film</typ>
        <popis>pohadka 2007</popis>
        <reziser ref="strach"/>
        <delka>60</delka>
    </porad>
    
    <porad id_poradu="prednosta">
        <nazev>Prednosta stanice</nazev>
        <typ>film</typ>
        <popis>1941</popis>
        <herci ref="burian"/>
        <delka>90</delka>
    </porad>
    
    <porad id_poradu="honza">
        <nazev>O linem Honzovi</nazev>
        <typ>film</typ>
        <popis>pohadka 1977</popis>
        <herci ref="eben"/>
        <delka>40</delka>
    </porad>
    
    <porad id_poradu="srdce">
        <nazev>Tri srdce</nazev>
        <typ>film</typ>
        <popis>pohadka 2007</popis>
        <herci ref="potm"/>
