=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/example/prg036_lukes_martin/data.dtd
<?xml version='1.0' encoding='windows-1252'?>

<!-- DTD k cviceni z predmetu XML, fotbalovy_zapas -->

<!ELEMENT fotbalovy_zapas (karty|fauly|goly|skore|rozhodci|muzstvo|zaznam)*>
<!ATTLIST fotbalovy_zapas
    jmeno_turnaje CDATA #FIXED "fotbalovy turnaj pseudohvezd">
<!ELEMENT muzstvo (sestava)?>
<!ATTLIST muzstvo
    domaci CDATA #REQUIRED
    id ID #REQUIRED
    hoste (ano|ne) "ano"
>

<!ELEMENT sestava (hrac+)*>

<!ELEMENT hrac (kapitan?|cislo)*>

<!ELEMENT cislo (#PCDATA|prezdivka|jmeno|zlute_fauly|cervene_fauly)*>
<!ATTLIST cislo
    id ID  #REQUIRED
  >

  <!ELEMENT zlute_fauly EMPTY>
  <!ATTLIST zlute_fauly id ID #REQUIRED>

  <!ELEMENT cervene_fauly EMPTY>
  <!ATTLIST cervene_fauly id ID #REQUIRED>

<!ELEMENT jmeno (#PCDATA)>

<!ELEMENT prezdivka (#PCDATA)>

<!ELEMENT kapitan (#PCDATA)>

<!ELEMENT rozhodci (vedlejsi|hlavni)*>

<!ELEMENT hlavni (prezdivka|jmeno)*>

<!ELEMENT vedlejsi EMPTY>

<!ELEMENT skore (vysledne|polocas)*>

<!ELEMENT polocas (#PCDATA)>

<!ELEMENT vysledne ANY>

<!ELEMENT goly (#PCDATA|skorujici_hrac)*>

<!ELEMENT skorujici_hrac EMPTY>

<!ATTLIST skorujici_hrac id_ref IDREF #REQUIRED>

<!ELEMENT fauly ANY>
 
<!ELEMENT karty (cervene|zlute)*>

<!ELEMENT zlute (#PCDATA|faulujici_zluty_hrac)*>
<!ELEMENT faulujici_zluty_hrac EMPTY>
<!ATTLIST faulujici_zluty_hrac id_ref IDREF #REQUIRED>


<!ELEMENT cervene (#PCDATA|faulujici_cerveny_hrac)*>

<!ELEMENT faulujici_cerveny_hrac EMPTY>
<!ATTLIST faulujici_cerveny_hrac id_ref IDREF #REQUIRED>
<!ELEMENT zaznam ANY>

<!-- Etity copyright a zadani zpusobuji problemy pri prohlizeni XML dokumentu v Mozzilla Firefox 
a Google Chrome, v IE a pri prohlizeni stranky v PSPadu ( Page Viewer ) funguje vse dobre-->
<!ENTITY copyright "Copyright: Martin Lukes, 30.9. 2009">
<!ENTITY zadani SYSTEM "zadani.xml">
<!ELEMENT zadani ANY>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/example/prg036_lukes_martin/data.xml
<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE fotbalovy_zapas SYSTEM "data.dtd">

<fotbalovy_zapas jmeno_turnaje="fotbalovy turnaj pseudohvezd">
    <muzstvo id="Horni_Dolni" domaci="ano" hoste="ne">
        <sestava>
            <hrac>
                <cislo id="A1">
                   1
                    <jmeno>
                     Jiri Paroubek
                    </jmeno>
                    <prezdivka>
                       buldozer
                    </prezdivka>
                </cislo>
                <kapitan>
                   ano
                </kapitan>
            </hrac>
            <hrac>
                <cislo id="A2" >
                   2
                    <jmeno>
                     Milos Melcak
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A3">
                   3
                    <jmeno>
                     Milos Zeman
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A4">
                   4
                    <jmeno>
                      Petra Buzkova
                    </jmeno>
                </cislo>
            </hrac>
            
            <hrac>
                <cislo id="A5">
                   5
                    <jmeno>
                     Stanislav Gross
                    </jmeno>
                </cislo>
            </hrac>
            
            <hrac>
                <cislo id="A6">
                   6
                    <jmeno>
                     Vladimir Spidla  
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A7">
                   7
                    <jmeno>
                     David Rath
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A8">
                   8
                    <jmeno>
                      Michal Pohanka
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A9">
                   9
                    <jmeno>
                        Bohuslav Sobotka
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A10">
                   10
                    <jmeno>
                      Vitezslav Jandak
                    </jmeno>
                    <prezdivka>
                       kecal
                    </prezdivka>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="A11">
                   11
                    <jmeno>
                      Zdenek Skromach
                    </jmeno>
                </cislo>
            </hrac>
        </sestava>
    </muzstvo>

    <muzstvo id="Dolni_Horni" domaci="ne">
        <sestava>
            <hrac>
                <cislo id="B1">
                   1
                    <jmeno>
                     Mirek Topolanek
                    </jmeno>
                </cislo>
                <kapitan>
                   ano
                </kapitan>
            </hrac>
            <hrac>
                <cislo id="B2">
                   2
                    <jmeno>
                     Vlastimil Tlusty
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="B3">
                   3
                    <jmeno>
                     Ivan Langer
                    </jmeno>
                </cislo>
            </hrac>
            <hrac>
                <cislo id="B4">
                   4
                    <jmeno>
                       Pavel Bem
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B5">
                   5
                    <jmeno>
                      Petr Necas
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B6">
                   6
                    <jmeno>
                     Jan Zahradil
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B7">
                   7
                 <cervene_fauly id="CB7"></cervene_fauly>
                    <jmeno>
                      Miroslav Macek
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B8">
                   8
                    <jmeno>
                      Lucie Talmanova
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B9">
                   9
                    <jmeno>
                       Petr Gandalovic
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B10">
                   10
                    <jmeno>
                       Petr Bendl
                    </jmeno>
                </cislo>
            </hrac>

            <hrac>
                <cislo id="B11">
                   11
                    <jmeno>
                       Miroslava Nemcova
                    </jmeno>
                </cislo>
            </hrac>

        </sestava>
    </muzstvo>

    <rozhodci>
        <hlavni>
            <jmeno>
           Vaclav Klaus
            </jmeno>
            <prezdivka>
           nestranny prezident
            </prezdivka>
        </hlavni>
        <vedlejsi/>
        <vedlejsi/>
    </rozhodci>
    <skore>
        <polocas>
                    1:1
        </polocas>
        <vysledne>
             1:2
        </vysledne>
    </skore>

    <goly>
        25. minuta dava <skorujici_hrac id_ref="A2"/> vlastni gol.
        36. minuta dava <skorujici_hrac id_ref="B2"/> vlastni gol.
        89. minuta dava <skorujici_hrac id_ref="B6"/> gol.
    </goly>
    
    <karty>
        <zlute>
        </zlute>
        <cervene>
             V 67. minute dostal <faulujici_cerveny_hrac id_ref="CB7"/> cervenou kartu a jeho
             tym odehraval v pocetni nevyhode.
        </cervene>
    </karty>
    <zaznam>
        Kratky sestrih zapasu Dolni_Horni &gt; Horni_Dolni.        
        <![CDATA[Kratky sestrih zapasu Dolni_Horni > Horni_Dolni.   ]]>
        <!-- rozdilny zapis, stejny vysledek jako sekce pred CDATA-->
        &copyright;
        Zadani DU : &zadani;
    </zaznam>


</fotbalovy_zapas>
