=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/XML/definice.dtd
<!ELEMENT definice (termin?,pojem?,vyznam+,viz?,zdroj?)>
<!ELEMENT termin (#PCDATA)>
<!ELEMENT pojem    (#PCDATA)>
<!ELEMENT vyznam   (#PCDATA|viz)*>
<!ELEMENT viz      (#PCDATA)>
<!ELEMENT zdroj	   (#PCDATA|em)*>
<!ELEMENT em (#PCDATA)>

<!ATTLIST viz link CDATA #IMPLIED>
<!ATTLIST zdroj link CDATA #REQUIRED>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/XML/definice-www5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definice SYSTEM "definice.dtd">
<definice>
	<pojem>World Wide Web</pojem>
	<vyznam>
		 (<viz>WWW</viz>, také pouze zkráceně <viz>web</viz>),
		 ve volném překladu „celosvětová pavučina“,
		 je označení pro aplikace internetového protokolu <viz>HTTP</viz>.
		 Je tím myšlena soustava propojených hypertextových dokumentů.
	</vyznam>
	<viz>Internet</viz>
	<zdroj link="blabla"><em>http://cs.wikipedia.org/wiki/Www</em></zdroj>
</definice>
