=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/prg036_martin_svoboda/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % address "(street, house_number, city, country, postcode)">
<!ENTITY % birthday "(day, month, year)">

<!ENTITY dia "Diabetes" >


<!ELEMENT flights (flight*)>
<!ELEMENT flight (passengers)>
<!ATTLIST flight
	id ID #REQUIRED
	number CDATA #REQUIRED
	date CDATA #REQUIRED
>

<!ELEMENT passengers (passenger*)>

<!-- Cestujici povinne jsou pouze trida a jmeno cestujiciho -->
<!ELEMENT passenger (
	class, seat?, first_name, middle_name?, last_name,
	birthday?, nationality?, passport?, address?,
	(notice,raw_notice)?
)>
<!-- infant_ref urcuje dite, ktere sedi dospeleho (nema vlastni sedacku) -->
<!ATTLIST passenger
	id ID #REQUIRED
	gender (MR|MRS|CHD|INF) #IMPLIED
	infant_ref IDREF #IMPLIED
>

<!ELEMENT class (#PCDATA)>
<!ELEMENT seat (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>

<!ELEMENT passport EMPTY>
<!ATTLIST passport
	number CDATA #REQUIRED
>
<!ELEMENT nationality (#PCDATA)>

<!ELEMENT birthday %birthday;>
	<!ELEMENT day (#PCDATA)>
	<!ELEMENT month (#PCDATA)>
	<!ELEMENT year (#PCDATA)>


<!ELEMENT address %address;>
<!ELEMENT street (#PCDATA)>
<!ELEMENT house_number (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>


<!ELEMENT notice (#PCDATA|separator)*>
<!ELEMENT separator EMPTY>
<!ELEMENT raw_notice (#PCDATA)>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/3.semestr/XML/xmlTesterbin/prg036_martin_svoboda/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flights SYSTEM "/workspace/school/xml/xml/src/data.dtd">
<?xml-stylesheet href="xyz.css" type="text/css"?>

<flights>
	<flight id="flight_1" number="TVS123" date="2009-10-10">
		<passengers>
			<!-- Cestujici s malym ditetem (dite nema pridelenou vlastni sedacku) -->
			<passenger id="pax_1" gender="MRS" infant_ref="pax_2">
				<class>C</class>
				<seat>12E</seat>
				<first_name>Jana</first_name>
				<middle_name>Petra</middle_name>
				<last_name>Nováková</last_name>
				<birthday>
					<day>10</day>
					<month>12</month>
					<year>1980</year>
				</birthday>
				<nationality>CZE</nationality>
				<passport number="123456"/>
				<address>
					<street>Dolní</street>
					<house_number>14</house_number>
					<city>Praha</city>
					<country>CZE</country>
					<postcode>10010</postcode>
				</address>
				<notice>
					Ticketless travel
					<separator/>
					&dia;
				</notice>
				<raw_notice>
					<![CDATA[
					ticketless travel,
					<b>diabetic</b>
					]]>
				</raw_notice>
			</passenger>
			
			<!-- Dite -->
			<passenger id="pax_2" gender="INF">
				<class>C</class>
				<first_name>Natálie</first_name>
				<last_name>Nováková</last_name>
				<birthday>
					<day>12</day>
					<month>4</month>
					<year>2003</year>
				</birthday>
				<notice>
					ticketless travel
				</notice>
				<raw_notice>
					<![CDATA[
					ticketless travel,
					]]>
				</raw_notice>
			</passenger>
			
			<passenger id="pax_3" gender="MR">
				<class>Y</class>
				<first_name>Petr</first_name>
				<last_name>Kratochvíl</last_name>
				<birthday>
					<day>10</day>
					<month>12</month>
					<year>1970</year>
				</birthday>
				<address>
					<street>Krátká</street>
					<house_number>10</house_number>
					<city>Praha</city>
					<country>CZE</country>
					<postcode>10100</postcode>
				</address>
			</passenger>
			
			<passenger id="pax_4" gender="MRS">
				<class>Y</class>
				<first_name>Pavla</first_name>
				<last_name>Nová</last_name>
				<birthday>
					<day>10</day>
					<month>1</month>
					<year>1991</year>
				</birthday>
				<address>
					<street>Jasná</street>
					<house_number>10</house_number>
					<city>Jablonec nad nisou</city>
					<country>CZE</country>
					<postcode>46606</postcode>
				</address>
			</passenger>
			
			<passenger id="pax_5" gender="MR">
				<class>C</class>
				<first_name>Pavel</first_name>
				<last_name>Janota</last_name>
				<birthday>
					<day>10</day>
					<month>8</month>
					<year>1971</year>
				</birthday>
				<address>
					<street>Nová</street>
					<house_number>10</house_number>
					<city>Praha</city>
					<country>CZE</country>
					<postcode>10100</postcode>
				</address>
			</passenger>
		</passengers>
	</flight>
	
	<flight id="flight_2" number="TVS124" date="2009-10-11">
		<passengers>
			<passenger id="pax_6" gender="MRS">
				<class>C</class>
				<first_name>Jana</first_name>
				<last_name>Svobodová</last_name>
				<birthday>
					<day>10</day>
					<month>12</month>
					<year>1980</year>
				</birthday>
				<address>
					<street>Stavební</street>
					<house_number>14</house_number>
					<city>Jablonec nad Nisou</city>
					<country>CZE</country>
					<postcode>46606</postcode>
				</address>
				<notice>
					diabetic
				</notice>
				<raw_notice>
					<![CDATA[
					<b>diabetic</b>
					]]>
				</raw_notice>
			</passenger>
			
			<passenger id="pax_7" gender="MR">
				<class>C</class>
				<first_name>Jan</first_name>
				<last_name>Svoboda</last_name>
				<birthday>
					<day>12</day>
					<month>4</month>
					<year>1978</year>
				</birthday>
				<address>
					<street>Stavební</street>
					<house_number>14</house_number>
					<city>Jablonec nad Nisou</city>
					<country>CZE</country>
					<postcode>46606</postcode>
				</address>
			</passenger>
			
			<passenger id="pax_8" gender="CHD">
				<class>C</class>
				<first_name>Petr</first_name>
				<last_name>Kratochvíl</last_name>
				<birthday>
					<day>10</day>
					<month>12</month>
					<year>2004</year>
				</birthday>
				<address>
					<street>Stavební</street>
					<house_number>14</house_number>
					<city>Jablonec nad Nisou</city>
					<country>CZE</country>
					<postcode>46606</postcode>
				</address>
			</passenger>
		</passengers>
	</flight>
</flights>
