=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/cv8/definice.dtd
<!ELEMENT definice (pojem,vyznam+,zdroj?)>
<!ELEMENT pojem    (#PCDATA)>
<!ELEMENT vyznam   (#PCDATA|viz)*>
<!ELEMENT viz      (#PCDATA)>
<!ELEMENT zdroj	   (#PCDATA)>

<!ATTLIST viz link CDATA #IMPLIED>
<!ATTLIST zdroj link CDATA #REQUIRED>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/cv8/definice-www2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definice SYSTEM "definice.dtd">
<definice>
	<pojem>WWW</pojem>
	<vyznam>
		World Wide Web je systém provázaných hypertextových dokumentů na Internetu.	 
	</vyznam>
	<vyznam>
		WorldWideWeb – první <viz>webový prohlížeč</viz>
	</vyznam>
	<vyznam>
		World Weather Watch – program pro sledování počasí Světové meteorologické organizace
	</vyznam>
	<vyznam>
		Wild Wild West – film z roku 1999 s <viz>Willem Smithem</viz> a Kevinem Klinem
	</vyznam>
	<vyznam>
		Wild West World – zábavní park v <viz>Park City</viz> v <viz>Kansasu</viz>
	</vyznam>
	<vyznam>
		The Wild Wild West – americký televizní seriál z šedesátých let dvacátého století
	</vyznam>
	<vyznam>
		Wild Wild West (hip hop) – název dvou hip hopových písní
	</vyznam>
	<vyznam>
		What a Wonderful World – název písně i knihy
	</vyznam>
	<vyznam>
		Wicked Witch of the West – postava z <viz>Čaroděj ze země Oz</viz>
	</vyznam>
	<vyznam>
		World Three – gang ze série videoher Megaman Battle Network
	</vyznam>
	<vyznam>
		Wolverine World Wide – výrobce obuvi s označením WWW
	</vyznam>
	<vyznam>
		WikiWikiWeb – první systém wiki
	</vyznam>
	<vyznam>
		Wimachtendienk Wingolauchsik Witahemui – tradiční princip amerických skautů
	</vyznam>
	<vyznam>
		Wicket Wystri Warrick – postava ze <viz>Star Wars</viz>
	</vyznam>
</definice>

=== CxsLucyfer/migrace_databaze/skola/Fel_bc/4.semestr/WMM/cv8/definice-www3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definice SYSTEM "definice.dtd">
<definice>
	<termin>World Wide Web</termin>
	<vyznam>
		 (<viz>WWW</viz>, také pouze zkráceně <viz>web</viz>),
		 ve volném překladu „celosvětová pavučina“,
		 je označení pro aplikace internetového protokolu <viz>HTTP</viz>.
		 Je tím myšlena soustava propojených hypertextových dokumentů.
	</vyznam>
	<viz>Internet</viz>
	<zdroj>http://cs.wikipedia.org/wiki/Www</zdroj>
</definice>
